// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// vec_at_id_fast
arma::vec vec_at_id_fast(const arma::mat& v);
RcppExport SEXP _riemtan_vec_at_id_fast(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_at_id_fast(v));
    return rcpp_result_gen;
END_RCPP
}
// similarity_transform
arma::mat similarity_transform(const arma::mat& A, const arma::mat& X);
RcppExport SEXP _riemtan_similarity_transform(SEXP ASEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(similarity_transform(A, X));
    return rcpp_result_gen;
END_RCPP
}
// symmpart_fast
arma::mat symmpart_fast(const arma::mat& A);
RcppExport SEXP _riemtan_symmpart_fast(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(symmpart_fast(A));
    return rcpp_result_gen;
END_RCPP
}
// safe_logm_cpp
arma::mat safe_logm_cpp(const arma::mat& X);
RcppExport SEXP _riemtan_safe_logm_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(safe_logm_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// airm_log_cpp
arma::mat airm_log_cpp(const arma::mat& sigma, const arma::mat& lambda);
RcppExport SEXP _riemtan_airm_log_cpp(SEXP sigmaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(airm_log_cpp(sigma, lambda));
    return rcpp_result_gen;
END_RCPP
}
// airm_exp_cpp
arma::mat airm_exp_cpp(const arma::mat& sigma, const arma::mat& v);
RcppExport SEXP _riemtan_airm_exp_cpp(SEXP sigmaSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(airm_exp_cpp(sigma, v));
    return rcpp_result_gen;
END_RCPP
}
// airm_vec_cpp
arma::vec airm_vec_cpp(const arma::mat& sigma, const arma::mat& v);
RcppExport SEXP _riemtan_airm_vec_cpp(SEXP sigmaSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(airm_vec_cpp(sigma, v));
    return rcpp_result_gen;
END_RCPP
}
// airm_unvec_cpp
arma::mat airm_unvec_cpp(const arma::mat& sigma, const arma::vec& w);
RcppExport SEXP _riemtan_airm_unvec_cpp(SEXP sigmaSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(airm_unvec_cpp(sigma, w));
    return rcpp_result_gen;
END_RCPP
}
// log_cholesky_log_cpp
arma::mat log_cholesky_log_cpp(const arma::mat& sigma, const arma::mat& lambda);
RcppExport SEXP _riemtan_log_cholesky_log_cpp(SEXP sigmaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_cholesky_log_cpp(sigma, lambda));
    return rcpp_result_gen;
END_RCPP
}
// log_cholesky_exp_cpp
arma::mat log_cholesky_exp_cpp(const arma::mat& sigma, const arma::mat& v);
RcppExport SEXP _riemtan_log_cholesky_exp_cpp(SEXP sigmaSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(log_cholesky_exp_cpp(sigma, v));
    return rcpp_result_gen;
END_RCPP
}
// spd_isometry_to_identity_cpp
arma::mat spd_isometry_to_identity_cpp(const arma::mat& sigma, const arma::mat& v);
RcppExport SEXP _riemtan_spd_isometry_to_identity_cpp(SEXP sigmaSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(spd_isometry_to_identity_cpp(sigma, v));
    return rcpp_result_gen;
END_RCPP
}
// spd_isometry_from_identity_cpp
arma::mat spd_isometry_from_identity_cpp(const arma::mat& sigma, const arma::mat& v);
RcppExport SEXP _riemtan_spd_isometry_from_identity_cpp(SEXP sigmaSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(spd_isometry_from_identity_cpp(sigma, v));
    return rcpp_result_gen;
END_RCPP
}
// scale_vector_for_unvec_cpp
arma::vec scale_vector_for_unvec_cpp(const arma::vec& w, int n);
RcppExport SEXP _riemtan_scale_vector_for_unvec_cpp(SEXP wSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_vector_for_unvec_cpp(w, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_riemtan_vec_at_id_fast", (DL_FUNC) &_riemtan_vec_at_id_fast, 1},
    {"_riemtan_similarity_transform", (DL_FUNC) &_riemtan_similarity_transform, 2},
    {"_riemtan_symmpart_fast", (DL_FUNC) &_riemtan_symmpart_fast, 1},
    {"_riemtan_safe_logm_cpp", (DL_FUNC) &_riemtan_safe_logm_cpp, 1},
    {"_riemtan_airm_log_cpp", (DL_FUNC) &_riemtan_airm_log_cpp, 2},
    {"_riemtan_airm_exp_cpp", (DL_FUNC) &_riemtan_airm_exp_cpp, 2},
    {"_riemtan_airm_vec_cpp", (DL_FUNC) &_riemtan_airm_vec_cpp, 2},
    {"_riemtan_airm_unvec_cpp", (DL_FUNC) &_riemtan_airm_unvec_cpp, 2},
    {"_riemtan_log_cholesky_log_cpp", (DL_FUNC) &_riemtan_log_cholesky_log_cpp, 2},
    {"_riemtan_log_cholesky_exp_cpp", (DL_FUNC) &_riemtan_log_cholesky_exp_cpp, 2},
    {"_riemtan_spd_isometry_to_identity_cpp", (DL_FUNC) &_riemtan_spd_isometry_to_identity_cpp, 2},
    {"_riemtan_spd_isometry_from_identity_cpp", (DL_FUNC) &_riemtan_spd_isometry_from_identity_cpp, 2},
    {"_riemtan_scale_vector_for_unvec_cpp", (DL_FUNC) &_riemtan_scale_vector_for_unvec_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_riemtan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
