# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vec_at_id_fast <- function(v) {
    .Call(`_riemtan_vec_at_id_fast`, v)
}

similarity_transform <- function(A, X) {
    .Call(`_riemtan_similarity_transform`, A, X)
}

symmpart_fast <- function(A) {
    .Call(`_riemtan_symmpart_fast`, A)
}

