# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vec_at_id_fast <- function(v) {
    .Call(`_riemtan_vec_at_id_fast`, v)
}

similarity_transform <- function(A, X) {
    .Call(`_riemtan_similarity_transform`, A, X)
}

symmpart_fast <- function(A) {
    .Call(`_riemtan_symmpart_fast`, A)
}

safe_logm_cpp <- function(X) {
    .Call(`_riemtan_safe_logm_cpp`, X)
}

airm_log_cpp <- function(sigma, lambda) {
    .Call(`_riemtan_airm_log_cpp`, sigma, lambda)
}

airm_exp_cpp <- function(sigma, v) {
    .Call(`_riemtan_airm_exp_cpp`, sigma, v)
}

airm_vec_cpp <- function(sigma, v) {
    .Call(`_riemtan_airm_vec_cpp`, sigma, v)
}

airm_unvec_cpp <- function(sigma, w) {
    .Call(`_riemtan_airm_unvec_cpp`, sigma, w)
}

bures_wasserstein_log_cpp <- function(sigma, lambda) {
    .Call(`_riemtan_bures_wasserstein_log_cpp`, sigma, lambda)
}

bures_wasserstein_exp_cpp <- function(sigma, v) {
    .Call(`_riemtan_bures_wasserstein_exp_cpp`, sigma, v)
}

log_cholesky_log_cpp <- function(sigma, lambda) {
    .Call(`_riemtan_log_cholesky_log_cpp`, sigma, lambda)
}

log_cholesky_exp_cpp <- function(sigma, v) {
    .Call(`_riemtan_log_cholesky_exp_cpp`, sigma, v)
}

spd_isometry_to_identity_cpp <- function(sigma, v) {
    .Call(`_riemtan_spd_isometry_to_identity_cpp`, sigma, v)
}

spd_isometry_from_identity_cpp <- function(sigma, v) {
    .Call(`_riemtan_spd_isometry_from_identity_cpp`, sigma, v)
}

scale_vector_for_unvec_cpp <- function(w, n) {
    .Call(`_riemtan_scale_vector_for_unvec_cpp`, w, n)
}

log_euclidean_log_cpp <- function(sigma, lambda) {
    .Call(`_riemtan_log_euclidean_log_cpp`, sigma, lambda)
}

log_euclidean_exp_cpp <- function(ref_pt, v) {
    .Call(`_riemtan_log_euclidean_exp_cpp`, ref_pt, v)
}

dexp_cpp <- function(a, x, num_points = 100L) {
    .Call(`_riemtan_dexp_cpp`, a, x, num_points)
}

dlog_cpp <- function(sigma, h, num_points = 100L) {
    .Call(`_riemtan_dlog_cpp`, sigma, h, num_points)
}

